 const students = [
  {
    id: "1",
    fullName: "Alimardon Mansurov",
    age: 17,
    phone: "+998901111111",
    email: "Ali@gmail.com",
    course: "Frontend Development",
    level: "Junior",
    progress: 72,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: "2",
    fullName: "Madina Rasulova",
    age: 16,
    phone: "+998901111112",
    email: "madina2@gmail.com",
    course: "React Native",
    level: "Beginner",
    progress: 48,
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: "3",
    fullName: "Azizbek Karimov",
    age: 18,
    phone: "+998901111113",
    email: "azizbek3@gmail.com",
    course: "Backend (NestJS)",
    level: "Middle",
    progress: 85,
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: "4",
    fullName: "Shahnoza Qodirova",
    age: 17,
    phone: "+998901111114",
    email: "shahnoza4@gmail.com",
    course: "UI/UX Design",
    level: "Beginner",
    progress: 63,
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: "5",
    fullName: "Javohir Tursunov",
    age: 19,
    phone: "+998901111115",
    email: "javohir5@gmail.com",
    course: "Fullstack Development",
    level: "Senior",
    progress: 91,
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: "6",
    fullName: "Dilnoza Islomova",
    age: 18,
    phone: "+998901111116",
    email: "dilnoza6@gmail.com",
    course: "Flutter",
    level: "Middle",
    progress: 74,
    image: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: "7",
    fullName: "Bekzod Abduvaliyev",
    age: 17,
    phone: "+998901111117",
    email: "bekzod7@gmail.com",
    course: "NodeJS",
    level: "Junior",
    progress: 58,
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: "8",
    fullName: "Malika Ergasheva",
    age: 16,
    phone: "+998901111118",
    email: "malika8@gmail.com",
    course: "Graphic Design",
    level: "Beginner",
    progress: 39,
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: "9",
    fullName: "Sardor Xudoyberdiyev",
    age: 18,
    phone: "+998901111119",
    email: "sardor9@gmail.com",
    course: "Python Backend",
    level: "Middle",
    progress: 80,
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: "10",
    fullName: "Gulbahor To‘xtayeva",
    age: 17,
    phone: "+998901111120",
    email: "gulbahor10@gmail.com",
    course: "React",
    level: "Junior",
    progress: 67,
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: "11",
    fullName: "Shaxzod Yo‘ldoshev",
    age: 19,
    phone: "+998901111121",
    email: "shaxzod11@gmail.com",
    course: "DevOps",
    level: "Senior",
    progress: 88,
    image: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: "12",
    fullName: "Nilufar Xasanova",
    age: 18,
    phone: "+998901111122",
    email: "nilufar12@gmail.com",
    course: "SMM",
    level: "Beginner",
    progress: 52,
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: "13",
    fullName: "Otabek Rahmonov",
    age: 17,
    phone: "+998901111123",
    email: "otabek13@gmail.com",
    course: "Java",
    level: "Middle",
    progress: 76,
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: "14",
    fullName: "Zarina Qosimova",
    age: 16,
    phone: "+998901111124",
    email: "zarina14@gmail.com",
    course: "Cyber Security",
    level: "Beginner",
    progress: 41,
    image: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: "15",
    fullName: "Bobur Aliyev",
    age: 18,
    phone: "+998901111125",
    email: "bobur15@gmail.com",
    course: "C++",
    level: "Middle",
    progress: 79,
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: "16",
    fullName: "Sevara Mirzayeva",
    age: 17,
    phone: "+998901111126",
    email: "sevara16@gmail.com",
    course: "UX Research",
    level: "Junior",
    progress: 69,
    image: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: "17",
    fullName: "Kamron Sobirov",
    age: 19,
    phone: "+998901111127",
    email: "kamron17@gmail.com",
    course: "Machine Learning",
    level: "Senior",
    progress: 93,
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: "18",
    fullName: "Laylo Normatova",
    age: 18,
    phone: "+998901111128",
    email: "laylo18@gmail.com",
    course: "Kotlin",
    level: "Middle",
    progress: 71,
    image: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: "19",
    fullName: "Farrux Usmonov",
    age: 17,
    phone: "+998901111129",
    email: "farrux19@gmail.com",
    course: "Angular",
    level: "Junior",
    progress: 62,
    image: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: "20",
    fullName: "Mohira Abdullayeva",
    age: 16,
    phone: "+998901111130",
    email: "mohira20@gmail.com",
    course: "Data Analysis",
    level: "Beginner",
    progress: 54,
    image: "https://randomuser.me/api/portraits/women/24.jpg",
  },
];